package handler

import (
	"fmt"
	mintcommon "mintserver/common"
	"mintserver/config"
	"unicode"
)

const (
	OK               uint32 = 0
	DBFAIL           uint32 = 1
	ACC_PSW_NO_MATCH uint32 = 2
	ACC_INVALID      uint32 = 3
	PSW_INVALID      uint32 = 4
	NAME_INVALID	 uint32 = 5
	ACC_EXISTED      uint32 = 6
	UNKNOWN_FUNC	 uint32 = 99	// Unknown function
)

// NewUser return the pointer of a new user
// The function is for user to call
// This shall never be called by the server
func NewUser(_account string, _name string, _psw string) *AppUser {
	au := &AppUser{Account: _account, Name: _name, Password: _psw}
	return au
}

// signIn checks the (Account, Password) pair
// Results of SignIn
//		a. Account and Password not matched, or may not exist. (ACC_PSW_NO_MATCH)
//		b. OK
//		c. DBFAIL
func signIn(_au *AppUser) (uint32) {
	defer func(){_au.Password = ""}() // mask password when finished
	if len(_au.Account) == 0 || len(_au.Account) > 25 || !isAlphaNum(_au.Account) {
		return ACC_INVALID
	}
	if len(_au.Password) == 0 || len(_au.Password) > 25 || !isAlphaNum(_au.Password) {
		return PSW_INVALID
	}
	result, err := signInTry(_au.Account, _au.ID, _au.Password)
	if err != nil {
		mintcommon.DebugPrint(config.GlobalConfiguration.EnableLog,
			config.GlobalConfiguration.LogToConsole,
			config.GlobalConfiguration.LogPath,
			fmt.Sprintf("[info] Database failed %s", err))
	}
	return result
}

// signUp an account
// 1. Check if (Account, Name, Password) are valid
// 2. Check if Account duplicated in database
// 3. Register the user, and fetch user id
// 4. Return Result
// Results of SignUp:
// 		a. Account not valid (ACC_INVALID)
//		b. Account already existed (ACC_EXISTED)
//		c. Password not valid (PSW_INVALID)
//		d. Name not valid (NAME_INVALID)
//		e. OK
//		f. DBFAIL
func signUp(_au *AppUser) (uint32) {
	defer func(){_au.Password = ""}() // mask password when finished
	if len(_au.Account) == 0 || len(_au.Account) > 25 || !isAlphaNum(_au.Account) {
		return ACC_INVALID
	}
	if len(_au.Password) == 0 || len(_au.Password) > 25 || !isAlphaNum(_au.Password) {
		return PSW_INVALID
	}
	if len(_au.Name) == 0 || len(_au.Name) > 25 {
		return NAME_INVALID
	}
	result, _id, err := signUpTry(_au.Account, _au.Name, _au.Password)
	if err != nil {
		mintcommon.DebugPrint(config.GlobalConfiguration.EnableLog,
			config.GlobalConfiguration.LogToConsole,
			config.GlobalConfiguration.LogPath,
			fmt.Sprintf("[info] Database failed %s", err))
	}
	if result == OK {
		_au.ID = _id	// _id is generated by database
	}
	return result
}

func isAlphaNum(str string) bool {
	for _, r := range str {
		if !unicode.IsDigit(r) && !unicode.IsLetter(r) {
			return false
		}
	}
	return true
}